#PBS -N rebx_07
#PBS -l select=1:ncpus=1:mem=1gb
#PBS -l walltime=03:00:00
#PBS -m abe
#PBS -q workq
set -x
trap "cd $PBS_O_WORKDIR;mkdir $PBS_JOBID;cp -R $TMPDIR/* $PBS_JOBID;exit" TERM
module load conda
source activate rebx-3.1.0
echo ----
echo Job started on `date`
echo Working on compute node `cat $PBS_NODEFILE`
cd $PBS_O_WORKDIR
echo PBS_O_WORKDIR is `pwd`
echo ----
python ./par100Myr.py
echo ----
echo Job ended at `date`
exit 0
