#PBS -l select=1:ncpus=1
#PBS -l walltime=00:15:00
#PBS -m abe
#PBS -M barons2@unlv.nevada.edu
#PBS -N script_test
#PBS -q small

set -x
trap "cd $PBS_O_WORKDIR;mkdir $PBS_JOBID;cp -R $TMPDIR/* $PBS_JOBID;exit" TERM
echo ----
echo Job started on `date`
echo Working on compute node `cat $PBS_NODEFILE`
cd $PBS_O_WORKDIR
echo PBS_O_WORKDIR is `pwd`
echo ----
echo This is a test.
echo ----
echo Job ended at `date`
exit 0
